Repository Pet-Mate-Project/Pet-Mate, pull requests merged in 2022-07, with the labels that each got.

#39 :sparkles: Add : Token 로컬스토리지에 저장
  src/pages/login/Login.jsx
Labels: Add more

#41 :sparkles: Add : 페이지별라우팅
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/pages/SetLogin.jsx
  src/pages/TempPage.jsx
  src/pages/login/Login.jsx
  src/pages/main/Main.jsx
  src/pages/main/Start.jsx
  src/template/InitPage.jsx
Labels: feature

#43 :sparkles: Add : 로그인,회원가입버튼라우팅
  src/App.js
  src/pages/SetLogin.jsx
  src/pages/main/Main.jsx
  src/style/globalStyle.js
Labels: feature, Add more

#45 Feat : 회원가입 프로필 업로드 기능
  src/App.js
  src/components/button/Button.jsx
  src/components/errorMessage/errorMessage.jsx
  src/components/profile/Profile.jsx
  src/components/profile/profileStyle.js
  src/pages/signUp/ProfilePage.jsx
  src/pages/signUp/SignUp.jsx
  src/pages/signUp/SignUpMain.jsx
Labels: feature

#47 :recycle: Modify : 회원가입 코드 전체적으로 개선
  src/App.js
  src/components/button/Button.jsx
  src/components/profile/Profile.jsx
  src/pages/signUp/ProfilePage.jsx
  src/pages/signUp/SignUp.jsx
  src/pages/signUp/SignUpMain.jsx
Labels: refactoring

#53 ✨ Feat : 회원가입 페이지 유효성 검사
  package-lock.json
  package.json
  src/components/button/Button.jsx
  src/components/errorMessage/errorMessage.jsx
  src/components/input/Input.jsx
  src/pages/signUp/ProfilePage.jsx
  src/pages/signUp/SignUp.jsx
  src/pages/signUp/SignUpMain.jsx
Labels: feature

#58 :lipstick: Style : delete-alert 컴포넌트생성
  src/components/deleteAlert/DeleteAlert.jsx
  src/components/deleteAlert/deleteStyle.js
Labels: components

#59 :truck: Modify : 폴더 구조 변경 components -> template -> pages
  src/App.js
  src/pages/InitPage.jsx
  src/pages/SetLogin.jsx
  src/pages/SignUpMain.jsx
  src/template/InitPage.jsx
  src/template/TempPage.jsx
  src/template/login/Login.jsx
  src/template/login/loginStyle.js
  src/template/main/Main.jsx
  src/template/main/Start.jsx
  src/template/main/mainStyle.js
  src/template/signUp/ProfilePage.jsx
  src/template/signUp/SignUp.jsx
  src/template/signUp/profilePageStyle.js
  src/template/signUp/signUpStyle.js
Labels: etc

#61 :lipstick: Style : animalBox컴포넌트
  src/assets/rang.jpg
  src/components/animalBox/AnimalBox.jsx
  src/components/animalBox/animalStyle.js
Labels: components

#62 💄 Add : SnSPost 컴포넌트 구현
  src/components/user/User.jsx
  src/template/snsPost/SnsPost.jsx
  src/template/snsPost/snsPostStyle.js
Labels: components

#64 :lipstick: Style : HomePost 컴포넌트 구현
  src/assets/pet-image.jpg
  src/components/button/Button.jsx
  src/components/user/User.jsx
  src/template/snsPost/HomePost.jsx
  src/template/snsPost/homePostStyle.js
Labels: components

#70 :lipstick: Style : 컴포넌트 디자인 및 속성 수정
  src/components/tabMenu/tabMenuStyle.js
  src/components/user/User.jsx
  src/components/user/userStyle.js
  src/template/post/HomePost.jsx
  src/template/post/SnsPost.jsx
  src/template/post/homePostStyle.js
  src/template/post/snsPostStyle.js
Labels: style

#73 🚧 Feat : 프로필 수정 기능 구현 중
  src/components/button/Button.jsx
  src/components/input/Input.jsx
  src/components/navBack/NavBack.jsx
  src/components/navBack/navBackStyle.js
  src/pages/SignUpMain.jsx
  src/style/commonLoginStyle.js
  src/template/profile/ProfileSet.jsx
  src/template/profileModify/ProfileModify.jsx
  src/template/profileModify/profileModifyStyle.js
  src/template/signUp/ProfilePage.jsx
Labels: feature, style

#76 :pencil2: Modify : 누락된글자추가
  src/template/signUp/ProfilePage.jsx
Labels: Add

#69 :lipstick: Style : 공통스타일수정
  src/pages/Homepage.jsx
  src/style/commonStyle.js
  src/template/login/Login.jsx
  src/template/main/Main.jsx
  src/template/main/Start.jsx
  src/template/signUp/ProfilePage.jsx
  src/template/signUp/SignUp.jsx
Labels: Add, style

#66 :lipstick: Style : 친구구하기버튼+로고 컴포넌트
  src/components/button/Button.jsx
  src/components/followCompo/FollowCompo.jsx
  src/components/followCompo/followCompoStyle.js
Labels: components

#77 :pencil2: Feat/컴포넌트경로수정
  src/template/profile/ProfileSet.jsx
Labels: bug

#79 :lipstick: Style : 아이콘버튼컴포넌트생성
  src/components/iconButton/IconButton.jsx
  src/components/iconButton/iconButton.js
Labels: style

#80 :lipstick: Style : 팔로우 리스트 UI구현 및 필요한 컴포넌트 속성 수정
  src/components/button/Button.jsx
  src/components/tabMenu/TabMenu.jsx
  src/components/tabMenu/tabMenuStyle.js
  src/components/user/User.jsx
  src/template/follow/Follow.jsx
  src/template/follow/followStyle.js
Labels: style

#83 💄Style : 전체적인 공통 스타일 수정
  src/pages/Homepage.jsx
  src/style/commonStyle.js
  src/template/TempPage.jsx
  src/template/follow/Follow.jsx
  src/template/follow/followStyle.js
  src/template/login/Login.jsx
  src/template/main/Main.jsx
  src/template/main/Start.jsx
  src/template/profileModify/ProfileModify.jsx
  src/template/profileModify/profileModifyStyle.js
  src/template/signUp/ProfilePage.jsx
  src/template/signUp/SignUp.jsx
Labels: style, refactoring

#84 :construction: Add : 유효성 불충족시 저장버튼 비활성화
  src/components/button/Button.jsx
  src/components/navBack/NavBack.jsx
  src/components/navBack/navBackStyle.js
  src/template/profileModify/ProfileModify.jsx
Labels: Add, style

#86 Feat/메인페이지
  src/components/followCompo/followCompoStyle.js
  src/components/iconButton/IconButton.jsx
  src/components/iconButton/iconButtonStyle.js
  src/components/navBack/navBackStyle.js
  src/pages/Homepage.jsx
  src/style/commonStyle.js
Labels: style

#91 :lipstick: Style : 피드페이지 UI
  src/pages/FeedPage.jsx
Labels: style

#93 :lipstick: Style : imgUploadBox컴포넌트
  src/components/imgUploadBox/ImgUploadBox.jsx
  src/components/imgUploadBox/imgUploadBoxStyle.js
Labels: style

#95 :lipstick: Style : 포스팅작성UI
  src/template/post/AddPost.jsx
Labels: style

#90 :sparkles: Feat : homepage라우팅 (승인하셔도 됩니당,, 깃그래프가 너무 길어질것같아서 ㅎㅎ)
  src/App.js
  src/pages/InitPage.jsx
  src/template/login/Login.jsx
Labels: feature

#97 :lipstick: Style : nav수정 (width값,saveNav분할)
  src/components/navBack/NavBack.jsx
  src/components/navBack/navBackStyle.js
  src/template/post/AddPost.jsx
  src/template/profileModify/ProfileModify.jsx
Labels: style

#100 :lipstick: Style : tabMenu width수정
  src/components/tabMenu/tabMenuStyle.js
Labels: Add, style

#102 :sparkles: Feat : 포스팅작성redux셋팅
  package-lock.json
  package.json
  src/index.js
  src/reducers/Reducer.js
  src/store.js
Labels: feature

#106 :truck: Modify : Homepage.jsx -> HomePage.jsx
  src/pages/HomePage.jsx
Labels: bug

#107 :lipstick: Style : 계정 검색 페이지 UI 구현
  src/components/search/AccountSearchBar.jsx
  src/template/search/AccountSearch.jsx
Labels: style

#110 :lipstick: Style : 모달 컴포넌트 구현
  src/components/postModal/PostModal.jsx
  src/components/postModal/postModalStyle.js
Labels: components

#108 Feat/포스팅작성기능
  src/components/button/Button.jsx
  src/components/imgUploadBox/ImgUploadBox.jsx
  src/components/imgUploadBox/imgUploadBoxStyle.js
  src/components/input/Input.jsx
  src/components/navBack/NavBack.jsx
  src/reducers/Reducer.js
  src/style/commonStyle.js
  src/template/post/AddPost.jsx
  src/template/profileModify/ProfileModify.jsx
Labels: feature, style

#114 :lipstick: Style : nav,input수정
  src/App.js
  src/components/followCompo/FollowCompo.jsx
  src/components/input/inputStyle.js
  src/components/navBack/NavBack.jsx
  src/components/navBack/navBackStyle.js
  src/pages/HomePage.jsx
Labels: style

#117 :sparkles: Modify : 계정 검색 페이지 컴포넌트 수정
  src/components/input/Input.jsx
  src/components/navBack/NavBack.jsx
  src/components/search/AccountSearchBar.jsx
  src/template/search/AccountSearch.jsx
Labels: components

#119 :sparkles: Add : 각 페이지 라우터 연결 및 뒤로가기 기능구현
  src/App.js
  src/components/iconButton/IconButton.jsx
  src/components/iconButton/iconButtonStyle.js
  src/components/navBack/NavBack.jsx
  src/components/profile/Profile.jsx
  src/components/tabMenu/TabMenu.jsx
  src/pages/HomePage.jsx
  src/template/profile/MyProfile.jsx
  src/template/profileModify/ProfileModify.jsx
  src/template/profileModify/profileModifyStyle.js
Labels: Add

#118 Feat/게시글불러오기(get요청)
  src/components/button/Button.jsx
  src/reducers/getPetInfoSlice.js
  src/store.js
  src/template/TempPage.jsx
  src/template/post/HomePost.jsx
  src/template/post/homePostStyle.js
  src/template/walkingFeed/WalkingFeed.jsx
Labels: feature, style

#127 :recycle: Feat : 버튼렌더링방식변경
  src/pages/HomePage.jsx
  src/reducers/getPetInfoSlice.js
  src/template/post/HomePost.jsx
  src/template/walkingFeed/DefaultFeed.jsx
Labels: feature, Add

#130 :adhesive_bandage: Modify : 게시글 리스트 nav,tab고정 및 세부사항 수정
  src/App.js
  src/components/postModal/postModalStyle.js
  src/components/tabMenu/TabMenu.jsx
  src/components/user/userStyle.js
  src/style/commonStyle.js
  src/template/chat/ChatList.jsx
  src/template/walkingFeed/WalkingFeed.jsx
Labels: Add, style

#136 :sparkles: Add : 피드작성자 프로필정보 및 사진등록
  src/components/profileIcon/ProfileIcon.jsx
  src/components/user/User.jsx
  src/template/post/HomePost.jsx
Labels: feature, Add

#137 :construction: Feat : 프로필수정기능 구현 및 회원정보 불러오기
  src/components/profile/Profile.jsx
  src/template/post/homePostStyle.js
  src/template/profile/MyProfile.jsx
  src/template/profileModify/ProfileModify.jsx
Labels: feature

#140 :lipstick: Add : 탭메뉴 선택시 배경컬러 고정기능 추가
  src/components/tabMenu/TabMenu.jsx
  src/components/tabMenu/tabMenuStyle.js
Labels: Add

#141 Feat/채팅룸페이지UI
  src/components/navBack/navBackStyle.js
  src/components/speechBubble/SpeechBubble.jsx
  src/components/speechBubble/speechBubbleStyle.js
  src/template/chat/ChatRoom.jsx
  src/template/chat/chatRoomStyle.js
Labels: components, style

#143 :sparkles: Modify : 로컬스토리지의 저장정보 변경
  src/pages/HomePage.jsx
  src/pages/InitPage.jsx
  src/reducers/getPetInfoSlice.js
  src/template/login/Login.jsx
  src/template/post/AddPost.jsx
  src/template/profile/MyProfile.jsx
  src/template/profileModify/ProfileModify.jsx
Labels: feature

#145 :lipstick: Add : Myprofile 하단부분 등록한 펫 리스트 추가
  src/components/animalBox/AnimalBox.jsx
  src/components/animalBox/animalStyle.js
  src/pages/MyProfilePage.jsx
  src/template/profilePost/PetPost.jsx
  src/template/profilePost/petPostStyle.js
Labels: Add

#144 :sparkles: Feat : 프로필 수정 후 화면에 반영 및 아이디수정 제한
  src/App.js
  src/components/button/Button.jsx
  src/components/input/Input.jsx
  src/components/input/inputStyle.js
  src/components/navBack/NavBack.jsx
  src/components/tabMenu/tabMenuStyle.js
  src/pages/SignUpMain.jsx
  src/template/login/Login.jsx
  src/template/post/AddPost.jsx
  src/template/post/HomePost.jsx
  src/template/profile/MyProfile.jsx
  src/template/profile/ProfileSet.jsx
  src/template/profileModify/ProfileModify.jsx
Labels: feature

#147 :lipstick: Modify : 누락된 라우터연결
  src/App.js
  src/components/tabMenu/TabMenu.jsx
  src/components/tabMenu/tabMenuStyle.js
  src/template/chat/ChatList.jsx
  src/template/follow/Follow.jsx
  src/template/follow/followStyle.js
  src/template/profile/MyProfile.jsx
Labels: Add

#149 :bug: Feat : 프로필사진url경로수정
  src/template/post/HomePost.jsx
Labels: bug

#148 :lipstick: Modify : NavWrapper관련 컴포넌트 속성 수정
  src/components/button/Button.jsx
  src/components/button/buttonStyle.js
  src/components/navBack/NavBack.jsx
  src/components/speechBubble/speechBubbleStyle.js
Labels: components, style

#151 :sparkles: Feat : Search페이지 라우팅 연결
  src/App.js
  src/components/navBack/NavBack.jsx
  src/pages/FeedPage.jsx
  src/pages/HomePage.jsx
Labels: feature

#152 Feat/sns업로드UI
  src/components/navBack/NavBack.jsx
  src/style/commonStyle.js
  src/template/profileModify/ProfileModify.jsx
  src/template/snsPost/AddSnsPost.jsx
  src/template/snsPost/SnsPost.jsx
  src/template/snsPost/addSnsPostStyle.js
  src/template/snsPost/snsPostStyle.js
Labels: style

#156 :sparkles: Feat : 여러이미지업로드(미리보기)
  src/template/snsPost/AddSnsPost.jsx
Labels: feature

#154 :sparkles: Add : 회원가입 후 로그인페이지로 연결 및 Id검증 오류해결
  src/pages/SignUpMain.jsx
  src/template/signUp/ProfilePage.jsx
Labels: Add

#157 Feat/게시글axios
  src/App.js
  src/assets/delete-btn.svg
  src/components/button/Button.jsx
  src/components/navBack/NavBack.jsx
  src/pages/FeedPage.jsx
  src/reducers/Reducer.js
  src/reducers/getPetInfoSlice.js
  src/template/snsPost/AddSnsPost.jsx
  src/template/snsPost/addSnsPostStyle.js
Labels: feature, style

#160 Feat/피드게시글렌더링
  src/components/user/User.jsx
  src/pages/FeedPage.jsx
  src/pages/MyProfilePage.jsx
  src/reducers/getPostSlice.js
  src/store.js
  src/template/snsFeed/DefaultSnsFeed.jsx
  src/template/snsFeed/SnsFeed.jsx
  src/template/snsPost/SnsPost.jsx
  src/template/snsPost/snsPostStyle.js
Labels: feature, style

#161 :sparkles: Feat : sns게시글 추가 후 업데이트된 상태렌더링
  src/template/snsPost/AddSnsPost.jsx
Labels: feature

#164 Feat/모달창라우팅
  src/components/deleteAlert/DeleteAlert.jsx
  src/components/deleteAlert/deleteStyle.js
  src/components/navBack/NavBack.jsx
  src/components/postModal/PostModal.jsx
Labels: feature, Add, style

#162 ♻️ Style :전체 컬러 색상코드 변수화 시켜서 반영
  src/components/animalBox/AnimalBox.jsx
  src/components/animalBox/animalStyle.js
  src/components/button/Button.jsx
  src/components/button/buttonStyle.js
  src/components/comment/commentStyle.js
  src/components/deleteAlert/deleteStyle.js
  src/components/errorMessage/errorStyle.js
  src/components/followCompo/followCompoStyle.js
  src/components/imgUploadBox/imgUploadBoxStyle.js
  src/components/input/inputStyle.js
  src/components/navBack/navBackStyle.js
  src/components/postModal/postModalStyle.js
  src/components/profileIcon/profileIconStyle.js
  src/components/speechBubble/speechBubbleStyle.js
  src/components/tabMenu/tabMenuStyle.js
  src/components/user/userStyle.js
  src/style/commonStyle.js
  src/style/globalColor.js
  src/template/chat/chatRoomStyle.js
  src/template/follow/Follow.jsx
  src/template/login/loginStyle.js
  src/template/post/homePostStyle.js
  src/template/profile/ProfileStyle.js
  src/template/profilePost/petPostStyle.js
  src/template/signUp/profilePageStyle.js
  src/template/snsPost/snsPostStyle.js
Labels: style, refactoring

#166 :sparkles: Feat : url로 직접 접근시 조건부렌더링
  src/App.js
  src/components/followCompo/FollowCompo.jsx
Labels: feature

#167 Revert ":sparkles: Feat : url로 직접 접근시 조건부렌더링"
  src/App.js
  src/components/followCompo/FollowCompo.jsx
Labels: quick

#171 :sparkles: Feat : 마이페이지 내게시글 랜더링 앨범형까지 구현완료
  src/template/profilePost/MyProfileSnsPost.jsx
  src/template/profilePost/SnsAlbum.jsx
  src/template/profilePost/SnsAlbumStyle.js
Labels: feature

#173 :sparkles: Feat : 로그아웃 클릭시 로컬스토리지에서 값 삭제
  src/components/deleteAlert/DeleteAlert.jsx
Labels: feature

#177 :sparkles: Feat : axios구문 try~catch문으로 수정
  src/pages/SignUpMain.jsx
  src/reducers/Reducer.js
  src/store.js
  src/template/login/Login.jsx
  src/template/post/AddPost.jsx
  src/template/profile/MyProfile.jsx
  src/template/profileModify/ProfileModify.jsx
  src/template/signUp/ProfilePage.jsx
  src/template/signUp/SignUp.jsx
  src/template/snsPost/AddSnsPost.jsx
Labels: Add, refactoring

#179 :sparkles: Feat : 검색리스트와 유저프로필 연결
  src/App.js
  src/pages/YourProfilePage.jsx
  src/template/profile/YourProfile.jsx
  src/template/search/AccountSearch.jsx
Labels: Add

#178 :sparkles: Add : dispatch를 추가하여 게시글렌더링버그 해결
  src/pages/MyProfilePage.jsx
Labels: bug, Add

#183 :lipstick: 내 프로필 pet게시글 클릭시 토글UI 구현
  src/components/animalBox/AnimalBox.jsx
  src/components/navBack/NavBack.jsx
  src/components/postModal/postModalStyle.js
  src/template/profilePost/PetPost.jsx
Labels: feature, style

#187 :sparkles: Feat : 팔로우, 언팔로우 기능 구현
  src/components/button/Button.jsx
  src/components/button/buttonStyle.js
  src/template/profile/YourProfile.jsx
Labels: feature

#185 :sparkles: Modify : 프로필수정 기본값 설정
  src/components/input/Input.jsx
  src/components/profile/Profile.jsx
  src/components/profile/profileStyle.js
  src/components/profileIcon/profileIconStyle.js
  src/template/profile/ProfileSet.jsx
  src/template/profileModify/ProfileModify.jsx
Labels: bug, Add

#188 Feat/내프로필pet게시글삭제기능
  src/components/deleteAlert/DeleteAlert.jsx
  src/components/postModal/PostModal.jsx
  src/reducers/deletePostSlice.js
  src/store.js
  src/template/profilePost/PetPost.jsx
  src/template/snsPost/SnsPost.jsx
Labels: feature

#184 Feat/검색기능
  src/template/search/AccountSearch.jsx
Labels: feature

#193 Feat/내프로필sns게시글삭제
  src/components/deleteAlert/DeleteAlert.jsx
  src/components/postModal/PostModal.jsx
  src/components/user/User.jsx
  src/components/user/userStyle.js
  src/template/profilePost/PetPost.jsx
  src/template/snsPost/SnsPost.jsx
Labels: feature, style

#191 :bug: Modify : 내프로필 사진 기본값 설정안되던 버그 해결
  src/components/input/Input.jsx
  src/components/profile/Profile.jsx
Labels: bug

#194 🐛 Modify : 내 프로필 앨범 형에서 여러 장의 사진 랜더링 안되는 오류 해결
  src/template/profilePost/SnsAlbum.jsx
Labels: bug

#196 :adhesive_bandage: Feat : 검색 페이지 이미지 props 추가
  src/template/search/AccountSearch.jsx
Labels: Add

#197 :sparkles: Feat : 유저프로필 게시글 랜더링
  src/pages/YourProfilePage.jsx
  src/template/search/AccountSearch.jsx
Labels: feature

#199 :sparkles: Feat : 팔로워, 팔로잉 리스트 랜더링
  src/App.js
  src/components/button/Button.jsx
  src/components/user/User.jsx
  src/template/follow/Follow.jsx
  src/template/follow/MyFollow.jsx
  src/template/follow/YourFollow.jsx
  src/template/profile/MyProfile.jsx
  src/template/profile/YourProfile.jsx
Labels: feature

#198 :bug: Modify : 프로필 사진 업로드 최대용량 제한
  src/components/profile/Profile.jsx
Labels: bug

#200 :sparkles: Feat : 피드게시판에 팔로워 게시글 랜더링
  src/pages/FeedPage.jsx
  src/template/snsPost/SnsPost.jsx
Labels: feature

#207 :bug: Mofify : 남의 게시글에서 (삭제,수정)토글 안보이게 수정
  src/pages/YourProfilePage.jsx
  src/template/profilePost/MyProfileSnsPost.jsx
  src/template/profilePost/PetPost.jsx
  src/template/snsPost/SnsPost.jsx
Labels: bug

#208 :sparkles: Add : 피드 게시글 클릭시 해당 유저 프로필로 이동
  src/components/user/User.jsx
  src/components/user/userStyle.js
Labels: Add

#210 Revert ":bug: Mofify : 남의 게시글에서 (삭제,수정)토글 안보이게 수정"
  src/pages/YourProfilePage.jsx
  src/template/profilePost/MyProfileSnsPost.jsx
  src/template/profilePost/PetPost.jsx
  src/template/snsPost/SnsPost.jsx
Labels: bug

#213 Feat/남의게시글토글제어
  src/pages/YourProfilePage.jsx
  src/template/postModify/PostModify.jsx
  src/template/profilePost/PetPost.jsx
Labels: bug, feature

#214 Feat/남의sns게시글토글제어
  src/components/button/Button.jsx
  src/template/post/AddPost.jsx
  src/template/snsFeed/SnsFeed.jsx
  src/template/snsPost/SnsPost.jsx
Labels: bug, Add

#212 :sparkles: Add : 팔로워/팔로잉 리스트에서 리스트 클릭시 해당 유저 프로필로 이동
  src/components/user/User.jsx
Labels: Add

#216 :bug: Modify : 프로필로 이동시 생기는 버그 수정
  src/components/user/User.jsx
Labels: bug

#220 Feat : 홈피드에 내가 팔로워한 사람의 펫매칭정보 불러오기
  src/pages/HomePage.jsx
  src/reducers/getFollowSlice.js
  src/store.js
  src/template/post/HomePost.jsx
  src/template/walkingFeed/WalkingFeed.jsx
Labels: feature

#219 :lipstick: Style : pet정보 input폼 textarea로 변경
  src/components/input/Input.jsx
  src/components/input/inputStyle.js
Labels: style

#218 Feat/내sns게시글수정
  src/App.js
  src/components/deleteAlert/DeleteAlert.jsx
  src/reducers/deletePostSlice.js
  src/template/postModify/PostModify.jsx
  src/template/profilePost/PetPost.jsx
  src/template/snsPost/AddSnsPost.jsx
  src/template/snsPost/SnsPost.jsx
  src/template/snsPostModify/SnsPostModify.jsx
Labels: feature

#222 :bug: Modify : 프로필 이미지가 뜨지않는 문제 수정
  src/components/user/User.jsx
Labels: bug

#223 :bug: Feat : 사진파일 크기 제한
  src/template/post/AddPost.jsx
  src/template/snsPost/AddSnsPost.jsx
Labels: bug

#225 :bug: Feat : react key error 해결
  src/template/main/Main.jsx
  src/template/post/HomePost.jsx
  src/template/profilePost/PetPost.jsx
  src/template/snsPost/SnsPost.jsx
Labels: bug

#226 Revert ":lipstick: Style : pet정보 input폼 textarea로 변경"
  src/components/input/Input.jsx
  src/components/input/inputStyle.js
Labels: quick

#228 Feat/textarea컴포넌트 생성 및 변수명등 크리티컬하지 않은 수정
  src/App.js
  src/components/deleteAlert/DeleteAlert.jsx
  src/components/input/Input.jsx
  src/components/input/inputStyle.js
  src/pages/HomePage.jsx
  src/pages/MyProfilePage.jsx
  src/reducers/getFollowSlice.js
  src/reducers/getPetInfoSlice.js
  src/reducers/getPostSlice.js
  src/template/post/AddPost.jsx
  src/template/postModify/PostModify.jsx
  src/template/snsPost/AddSnsPost.jsx
  src/template/snsPostModify/SnsPostModify.jsx
Labels: Add, later

#230 :art: Modify : 코드 개선 및 라우팅 추가
  src/components/user/User.jsx
Labels: Add, refactoring

#232 :memo: Modify : 기본 내용 추가
  README.md
Labels: document

#234 Feat : RTK 공통slice를 이용해 생긴 버그잡기
  src/App.js
  src/pages/HomePage.jsx
  src/reducers/getAllpetInfoSlice.js
  src/reducers/getPetInfoSlice.js
  src/store.js
Labels: quick

#236 :truck: Modify : post 폴더명 변경
  src/App.js
  src/template/homePost/AddPost.jsx
  src/template/homePost/HomePost.jsx
  src/template/homePost/homePostStyle.js
  src/template/walkingFeed/WalkingFeed.jsx
Labels: etc

#238 Feat/post컴포넌트구현
  src/components/post/FeedPost.jsx
  src/components/post/feedPostStyle.js
  src/template/snsFeed/SnsFeed.jsx
  src/template/snsPost/SnsPost.jsx
Labels: components

#239 Feat/feed렌더링버그
  src/pages/FeedPage.jsx
  src/pages/MyProfilePage.jsx
  src/template/snsPostModify/SnsPostModify.jsx
Labels: bug

#241 :lipstick: Style : 홈피드 스타일 변경
  src/components/button/Button.jsx
  src/template/homePost/HomePost.jsx
  src/template/homePost/homePostStyle.js
Labels: style

#244 :sparkles: Feat : 게시글 상세페이지 구현
  src/App.js
  src/components/comment/Comment.jsx
  src/components/comment/commentStyle.js
  src/components/post/FeedPost.jsx
  src/components/post/feedPostStyle.js
  src/reducers/getPostDetailSlice.js
  src/template/postDetail/FeedPostDetail.jsx
  src/template/postDetail/FeedPostDetailStyle.js
  src/template/profilePost/MyProfileSnsPost.jsx
  src/template/snsFeed/SnsFeed.jsx
  src/template/snsPost/SnsPost.jsx
Labels: feature, style

#242 :sparkles: Feat : 계정 검색 결과와 일치하는 문자 색상 변경
  src/components/user/User.jsx
  src/template/search/AccountSearch.jsx
Labels: feature

#249 Feat/사진업로드크기수정
  src/pages/YourProfilePage.jsx
  src/template/snsPost/AddSnsPost.jsx
  src/template/snsPost/addSnsPostStyle.js
  src/template/snsPostModify/SnsPostModify.jsx
Labels: Add

#250 :lipstick: Style : 좋아요토글UI
  src/components/post/FeedPost.jsx
Labels: Add

#247 :bug: Modify : 게시글 정보가 저장된 postDetail이 undefined일 때 생기는 에러 수정
  src/template/postDetail/FeedPostDetail.jsx
Labels: bug, Add, quick

#251 :truck: Feat : store에 import하는 명칭 통일 (reducer로)
  src/store.js
Labels: Add

#252 :bug: Modify : 팔로워, 팔로잉 리스트에 들어갔을 때 첫랜더링 문제로 버튼이 깜박이는 이슈 해결
  src/components/user/User.jsx
  src/template/profile/YourProfile.jsx
Labels: bug

#253 Feat/댓글기능
  package-lock.json
  package.json
  src/components/comment/Comment.jsx
  src/components/commentList/CommentList.jsx
  src/components/commentList/commentListStlye.js
  src/components/post/FeedPost.jsx
  src/reducers/getCommentSlice.js
  src/store.js
  src/template/postDetail/FeedPostDetail.jsx
Labels: feature, style

#256 :sparkles: Feat : 홈 로딩바 구현
  package-lock.json
  package.json
  src/pages/HomePage.jsx
Labels: feature

#258 :bug: Modify : 계정 검색 결괏값 출력
  src/components/errorMessage/errorStyle.js
  src/template/search/AccountSearch.jsx
Labels: bug, refactoring

#262 Feat/상세보기새로고침버그
  src/App.js
  src/components/post/FeedPost.jsx
  src/template/postDetail/FeedPostDetail.jsx
Labels: bug

#264 Modify : 오류수정
  src/components/post/FeedPost.jsx
  src/template/snsPost/SnsPost.jsx
Labels: bug

#263 :bug: Feat : 댓글업데이트 버그 수정
  src/reducers/getCommentSlice.js
  src/template/postDetail/FeedPostDetail.jsx
Labels: bug

#266 ✨ Feat : 산책(펫)게시글 상세페이지 구현
  src/App.js
  src/components/post/FeedPost.jsx
  src/reducers/getPostDetailSlice.js
  src/template/homePost/HomePost.jsx
  src/template/postDetail/FeedPostDetail.jsx
  src/template/postDetail/WalkingPostDetail.jsx
  src/template/postDetail/walkingPostDetailStyle.js
  src/template/profilePost/PetPost.jsx
Labels: feature, style

#268 :sparkles: Feat : 댓글토글버튼구현
  src/components/comment/Comment.jsx
  src/components/commentList/CommentList.jsx
  src/components/deleteAlert/DeleteAlert.jsx
  src/reducers/getCommentSlice.js
  src/template/postDetail/FeedPostDetail.jsx
Labels: feature

#269 :bug: Feat : 토글배경 검정색으로 나오는 오류
  src/components/commentList/CommentList.jsx
  src/template/postDetail/FeedPostDetail.jsx
  src/template/profilePost/PetPost.jsx
Labels: bug

#275 ✨ Add : 앨범형 게시글 클시 상세페이지로 이동
  src/style/commonStyle.js
  src/style/globalStyle.js
  src/template/profilePost/SnsAlbum.jsx
Labels: feature, Add, style

#273 :lipstick: Style : 폰트 지정 및 Link로 인한 폰트컬러 변경
  src/App.css
  src/App.js
  src/components/animalBox/animalStyle.js
  src/components/post/FeedPost.jsx
  src/style/fonts/SUIT-Bold.woff2
  src/style/fonts/SUIT-ExtraLight.woff2
  src/style/fonts/SUIT-Medium.woff2
  src/style/fonts/SUIT-SemiBold.woff2
  src/style/globalStyle.js
  src/template/homePost/homePostStyle.js
Labels: style

#272 Feat/업데이트버그
  src/components/post/FeedPost.jsx
  src/pages/HomePage.jsx
Labels: bug

#279 :bug: Modify : 팀마다 이미지 업로드 방식이 다양하여 이미지가 안뜨는 이슈 수정
  src/components/commentList/CommentList.jsx
  src/components/post/FeedPost.jsx
  src/components/user/User.jsx
  src/template/homePost/HomePost.jsx
  src/template/postDetail/FeedPostDetail.jsx
  src/template/postDetail/WalkingPostDetail.jsx
  src/template/profile/MyProfile.jsx
  src/template/profile/YourProfile.jsx
  src/template/profilePost/PetPost.jsx
Labels: bug

#280 :recycle: Feat : 접근성을 위한 코드 리팩토링
  src/components/animalBox/AnimalBox.jsx
  src/components/commentList/CommentList.jsx
  src/components/iconButton/IconButton.jsx
  src/components/navBack/NavBack.jsx
  src/components/post/FeedPost.jsx
  src/components/profileIcon/ProfileIcon.jsx
  src/components/user/User.jsx
  src/components/user/userStyle.js
  src/template/homePost/HomePost.jsx
  src/template/profilePost/MyProfileSnsPost.jsx
  src/template/profilePost/myProfileSnsPostStyle.js
Labels: refactoring

#277 :lipstick: Style : Input 안쪽여백 추가
  src/components/input/inputStyle.js
Labels: style

#284 :sparkles: Feat : 파비콘, 타이틀 추가
  public/favicon.ico
  public/index.html
Labels: Add

#285 :bug: Feat : 첫 접속시 토큰검증API를 사용하여 검증
  src/pages/InitPage.jsx
  src/reducers/verifyTokenSlice.js
  src/store.js
Labels: bug

#286 Revert ":bug: Feat : 첫 접속시 토큰검증API를 사용하여 검증"
  src/pages/InitPage.jsx
  src/reducers/verifyTokenSlice.js
  src/store.js
Labels: bug

#287 Feat/디테일페이지오류수정
  src/template/postDetail/FeedPostDetail.jsx
Labels: bug

#288 Feat/첫접속시토큰검증에러
  src/pages/InitPage.jsx
  src/reducers/verifyTokenSlice.js
  src/store.js
  src/template/login/Login.jsx
Labels: bug

#290 :bug: Feat : 기존 게시글 업로드시 이미지 src가 안들어온채 렌더링된 부분 수정
  src/components/imgUploadBox/ImgUploadBox.jsx
  src/components/imgUploadBox/imgUploadBoxStyle.js
Labels: bug

#291 Feat/이미지업로드방식변경
  src/components/profile/Profile.jsx
  src/pages/SignUpMain.jsx
  src/template/homePost/AddPost.jsx
  src/template/profilePost/SnsAlbum.jsx
  src/template/snsPost/AddSnsPost.jsx
Labels: bug

#293 :lipstick: Style : 로그인/회원가입에서 input 및 글자 크기 조정
  src/components/errorMessage/errorStyle.js
  src/components/input/inputStyle.js
  src/style/commonStyle.js
  src/style/globalStyle.js
  src/template/login/Login.jsx
  src/template/login/loginStyle.js
  src/template/profile/ProfileSet.jsx
  src/template/search/AccountSearch.jsx
  src/template/signUp/SignUp.jsx
Labels: style

#294 :adhesive_bandage: Modify : 이미지 경로 변경
  src/template/homePost/AddPost.jsx
Labels: Add

#295 :adhesive_bandage: Modify : 내프로필에서 디테일페이지 댓글 달면 랜더링 안되는 오류해결
  src/components/post/FeedPost.jsx
Labels: bug

#299 :lipstick: Modify : 팔로우리스트 limit 제한 및 스타일 수정
  src/components/profileIcon/ProfileIcon.jsx
  src/style/commonStyle.js
  src/template/follow/MyFollow.jsx
  src/template/follow/YourFollow.jsx
  src/template/follow/followStyle.js
Labels: feature, Add, style

#297 :bug: Feat : 댓글리스트렌더링시 이전 댓글이 잠깐 보이는 현상 제거
  src/template/postDetail/FeedPostDetail.jsx
Labels: bug

#300 :bug: Feat : 디테일페이지에 들어가서 특정 section을 클릭했을경우 사진 깜빡임 문제
  src/components/post/FeedPost.jsx
  src/components/user/userStyle.js
  src/template/snsPost/SnsPost.jsx
Labels: bug

#302 Feat : 회원가입 비밀번호 확인 기능 추가
  src/components/input/Input.jsx
  src/pages/SignUpMain.jsx
  src/template/signUp/SignUp.jsx
Labels: feature

#303 :adhesive_bandage: Feat : import안된 컴포넌트 import
  src/components/imgUploadBox/ImgUploadBox.jsx
Labels: bug, Add

#304 Feat/유저정보리덕스
  src/components/imgUploadBox/ImgUploadBox.jsx
  src/reducers/getUserInfoSlice.js
  src/store.js
  src/template/homePost/HomePost.jsx
  src/template/login/Login.jsx
  src/template/postDetail/FeedPostDetail.jsx
  src/template/profile/MyProfile.jsx
  src/template/profileModify/ProfileModify.jsx
Labels: refactoring

#308 💄 Style : splash화면 애니메이션 추가
  src/assets/after-logo.svg
  src/assets/before-logo.svg
  src/assets/main-logo.svg
  src/template/main/Main.jsx
  src/template/main/Start.jsx
  src/template/main/mainStyle.js
Labels: style

#309 :art: Modify : import코드 순서변경 및 사용되지않는 코드 삭제
  src/pages/FeedPage.jsx
  src/pages/HomePage.jsx
  src/pages/InitPage.jsx
  src/pages/MyProfilePage.jsx
  src/pages/SignUpMain.jsx
  src/pages/YourProfilePage.jsx
  src/template/follow/MyFollow.jsx
  src/template/follow/YourFollow.jsx
  src/template/homePost/AddPost.jsx
  src/template/homePost/HomePost.jsx
  src/template/login/Login.jsx
  src/template/main/Main.jsx
  src/template/postDetail/FeedPostDetail.jsx
  src/template/postDetail/WalkingPostDetail.jsx
  src/template/postModify/PostModify.jsx
  src/template/profile/MyProfile.jsx
  src/template/profile/YourProfile.jsx
  src/template/profileModify/ProfileModify.jsx
  src/template/profilePost/PetPost.jsx
  src/template/profilePost/SnsAlbum.jsx
  src/template/search/AccountSearch.jsx
  src/template/signUp/ProfilePage.jsx
  src/template/signUp/SignUp.jsx
  src/template/snsPost/AddSnsPost.jsx
  src/template/snsPost/SnsPost.jsx
  src/template/snsPostModify/SnsPostModify.jsx
Labels: etc

#313 :adhesive_bandage: Style : 화면 축소시 deleteAlert가 깨지는 UI 수정
  src/components/deleteAlert/DeleteAlert.jsx
  src/components/deleteAlert/deleteStyle.js
Labels: bug, style

#315 :bug: Modify : 페이지에 안맞게 뜨는 팝업창 수정
  src/components/navBack/NavBack.jsx
Labels: bug, Add

#316 :bug: Feat : 사진경로가 수정됨에 따른 코드 수정
  src/template/postModify/PostModify.jsx
  src/template/snsPostModify/SnsPostModify.jsx
Labels: bug

#318 Feat/수정페이지새로고침버그
  src/App.js
  src/components/post/FeedPost.jsx
  src/template/postModify/PostModify.jsx
  src/template/profilePost/PetPost.jsx
  src/template/snsPostModify/SnsPostModify.jsx
Labels: bug

#323 :memo: Modify : 내용 수정
  README.md
Labels: document

#319 Modify : 코드수정으로 인해 프로필수정시 default값 적용 안되던 에러 해결
  src/components/profile/Profile.jsx
  src/template/profile/ProfileSet.jsx
  src/template/profileModify/ProfileModify.jsx
Labels: bug

#321 Feat/UI디테일수정
  src/components/post/FeedPost.jsx
  src/components/post/feedPostStyle.js
  src/pages/FeedPage.jsx
  src/pages/MyProfilePage.jsx
  src/template/homePost/homePostStyle.js
Labels: style

#326 :lipstick: Modify : 404페이지 이전 페이지 버튼 수정
  src/components/followCompo/FollowCompo.jsx
Labels: components

#325 📝 Add : 리드미 담당 기능 추가
  README.md
Labels: document

#329 :speech_balloon: Modify : 특수문자 수정
  src/components/followCompo/FollowCompo.jsx
  src/template/profile/MyProfile.jsx
  src/template/profile/YourProfile.jsx
Labels: later
