Repository Pet-Mate-Project/Pet-Mate, pull requests merged in 2022-08, with the labels that each got.

#386 :ambulance: Bug : input 입력될 때 마다 이미지 post되는 오류 해결
  src/pages/SignUpMain.jsx
Labels: bug

#387 Add/meta태그추가
  README.md
  src/pages/FeedPage.jsx
  src/pages/HomePage.jsx
  src/pages/MyProfilePage.jsx
  src/template/chat/ChatList.jsx
  src/template/login/Login.jsx
  src/template/search/AccountSearch.jsx
Labels: refactoring

#390 Feat : 댓글,게시글 신고하기 기능 & 상세페이지에서 내 게시글 삭제 기능 구현
  src/components/deleteAlert/DeleteAlert.jsx
  src/components/post/FeedPost.jsx
  src/components/postModal/PostModal.jsx
  src/reducers/reportPostSlice.js
  src/template/postDetail/FeedPostDetail.jsx
Labels: bug, feature
